{% set name = "cmrt" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/{{ name }}/archive/{{ version }}.tar.gz
  fn: cmrt-{{ version }}.tar.gz
  sha256: ca22e905a2717fc740e703e65a0061a0e11f4ea513ba970bbc10b3bd6d28e6e0

build:
  skip: True  # [not linux]
  number: 1001
  # https://github.com/intel/cmrt/blob/master/NEWS
  run_exports:
    - {{ pin_subpackage('cmrt', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
  host:
    - libdrm
    - libva

test:
  commands:
    - test -f $PREFIX/include/cm_rt.h
    - test -f $PREFIX/include/cm_rt_linux.h

about:
  home: https://github.com/intel/cmrt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Media GPU kernel manager for Intel G45 & HD Graphics family'
  description: |
    One solution to expose Intel’s Gen GPU’s high performance through high
    level language.

extra:
  recipe-maintainers:
    - hmaarrfk
